// <auto-generated />
using System;
using Ch15Lab.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ch15Lab.Data.Migrations
{
    [DbContext(typeof(POManagerContext))]
    partial class POManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Ch15Lab.Data.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AddressId");

                    b.HasIndex("StateId");

                    b.ToTable("Address", (string)null);

                    b.HasData(
                        new
                        {
                            AddressId = 10001,
                            City = "Holland",
                            PostalCode = "49424",
                            StateId = 26,
                            Street = "321 Fisrt Ave.",
                            Title = "Ox Exports Main Office"
                        },
                        new
                        {
                            AddressId = 10002,
                            City = "Holland",
                            PostalCode = "49424",
                            StateId = 26,
                            Street = "123 Last Ln.",
                            Title = "Ox Exports Warehouse"
                        },
                        new
                        {
                            AddressId = 10003,
                            City = "Columbus",
                            PostalCode = "43229",
                            StateId = 39,
                            Street = "987 Easy St.",
                            Title = "Nicks Nacks Headquarters"
                        });
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1001,
                            AddressId = 10001,
                            Name = "Ox Imports"
                        },
                        new
                        {
                            CustomerId = 1002,
                            AddressId = 10003,
                            Name = "Nicks Nacks"
                        });
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("SkuNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("VendorId");

                    b.ToTable("InventoryItem", (string)null);

                    b.HasData(
                        new
                        {
                            InventoryItemId = 20001,
                            Cost = 85.17m,
                            Count = 17,
                            Description = "This particular vase features a traditional windmill design combined with the floral motif, handpainted in blue & white. This piece is approximately 30cm (12\") tall. Each piece is completely handpainted, marked with the factory mark, item number, and the artist's initials. Each and every piece comes with a certificate of authenticity.",
                            RetailPrice = 141.95m,
                            SkuNumber = "010095_11",
                            Title = "DeWit Handpainted 12\" Blue Delft Vase",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20002,
                            Cost = 35.97m,
                            Count = 8,
                            Description = "This particular vase features either a traditional windmill or floral design handpainted in blue & white. This piece is approximately 8\" tall. Each piece is completely handpainted, marked with the factory mark, item number, and the artist's initials. Each and every piece comes with a certificate of authenticity.",
                            RetailPrice = 59.95m,
                            SkuNumber = "010096_1x",
                            Title = "DeWit Handpainted 8\" Blue Delft Vase",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20003,
                            Cost = 51.57m,
                            Count = 6,
                            Description = "This particular vase features a traditional floral design, handpainted in blue & white. This piece is approximately 22cm (9\") tall. Each piece is completely handpainted, marked with the factory mark, item number, and the artist's initials. Each and every piece comes with a certificate of authenticity.",
                            RetailPrice = 85.95m,
                            SkuNumber = "011947_12",
                            Title = "DeWit Handpainted Blue & White Delft Six-Sided Vase",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20004,
                            Cost = 32.37m,
                            Count = 72,
                            Description = "Available in either the classic floral design or the traditional windmill design, this charming hand-painted ornament is a great combination of two favorites: real, true hand-painted, made-in-Holland delft, and the collectability of Christmas items. Each piece of DeWit delft is marked with the factory's mark, item number, and artist's initials. Also includes a certificate of authenticity. This ornament is approximately 7cm (3\") tall.",
                            RetailPrice = 53.95m,
                            SkuNumber = "011527_xx",
                            Title = "DeWit Ball Christmas Ornament Floral or Windmill Design",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20005,
                            Cost = 16.98m,
                            Count = 94,
                            Description = "Featuring either the classic floral or windmill design, these charming hand-painted ornaments are a great combination of two favorites: real, true hand-painted, made-in-Holland delft, and the collectibility of Christmas items. Each piece of DeWit delft is marked with the factory's mark, item number, and artist's initials. Also includes a certificate of authenticity. This ornament is approximately 6cm (2.5\") tall.",
                            RetailPrice = 33.95m,
                            SkuNumber = "011524_xx",
                            Title = "DeWit Top Shape Christmas Ornament",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20006,
                            Cost = 64.17m,
                            Count = 3,
                            Description = "This wonderful hand-painted delft teapot will make tea-time a truly special event! This teapot is available with either a traditional windmill or floral design. Each piece of DeWit delft is marked with the factory's mark, item number, and artist's initials. Also includes a certificate of authenticity. This item is approximately 6.25\" tall, by 10\" wide.",
                            RetailPrice = 106.95m,
                            SkuNumber = "010761_1x",
                            Title = "DeWit Delft Teapot, 6.25\"",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20007,
                            Cost = 71.97m,
                            Count = 2,
                            Description = "This wonderful hand-painted delft teapot will make tea-time a truly special event! This teapot is available with either a traditional windmill or floral design. Select your design choice above. Each piece of DeWit delft is marked with the factory's mark, item number, and artist's initials. Also includes a certificate of authenticity. This item is approximately 10\" tall.",
                            RetailPrice = 119.95m,
                            SkuNumber = "010760_1x",
                            Title = "DeWit Delft Handpainted Teapot",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20008,
                            Cost = 80.97m,
                            Count = 12,
                            Description = "This beautiful hand-painted set will make tea-time a truly special event! The sugar & creamer set is available with either a traditional windmill or floral design, handpainted in blue & white. Each piece of DeWit delft is marked with the factory's mark, item number, and artist's initials. Also includes a certificate of authenticity.",
                            RetailPrice = 134.95m,
                            SkuNumber = "010762_1x",
                            Title = "DeWit Handpainted Blue Delft Sugar & Creamer",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20009,
                            Cost = 98.37m,
                            Count = 9,
                            Description = "This charming Tea-For-One set is handpainted in Holland and is available in the traditional blue and white windmill motif, the beautiful blue and white floral design, or the stunning multi-color floral painting. Teapot holds approximately 14 oz of liquid. A beautiful gift for yourself or for the tea lover in your life. Please select your design choice from the pull-down menu above. Each piece of DeWit delft is marked with the factory's mark, item number, and artist's initials. Also includes a certificate of authenticity.",
                            RetailPrice = 163.95m,
                            SkuNumber = "011420_xx",
                            Title = "DeWit Handpainted Tea for One Set",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20010,
                            Cost = 25.17m,
                            Count = 38,
                            Description = "Decorative circular plate is a must-have for the any delft collector. Decorated with a classic Dutch windmill design, this charming plate is the perfect addition to your curio cabinet. Each piece carries the full factory markings, which includes the factory mark, item number, artist's initials, and the date code, and is delivered with a certificate of authenticity. This piece is approximately 5.5\" in diameter.",
                            RetailPrice = 41.95m,
                            SkuNumber = "010923_1x",
                            Title = "DeWit Handpainted Blue Delft Serving Plate",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20011,
                            Cost = 20.97m,
                            Count = 45,
                            Description = "Coffee with class and distinction. This mug will quickly become your favorite, both in function and beauty. It is marked with the DeWit factory mark, and comes with a certificate of authenticity! Handpainted with a blue windmill or floral design, this is a true classic. This mug is approximately 4\" tall.",
                            RetailPrice = 34.95m,
                            SkuNumber = "010777_1x",
                            Title = "DeWit Handpainted Coffee Mug",
                            VendorId = 101
                        },
                        new
                        {
                            InventoryItemId = 20012,
                            Cost = 37.17m,
                            Count = 16,
                            Description = "This particular windmill features a traditional blue and white windmill design handpainted on the windmill itself. This piece is approximately 9.5\" tall. Each DeWit piece is completely handpainted, marked with the factory mark, item number, and the artist's initials. Each and every piece comes with a certificate of authenticity.",
                            RetailPrice = 61.95m,
                            SkuNumber = "010483_12",
                            Title = "DeWit Handpainted Blue and White Delft Ceramic Windmill - 9.5\"",
                            VendorId = 101
                        });
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatus", (string)null);

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            Description = "Ordered"
                        },
                        new
                        {
                            OrderStatusId = 2,
                            Description = "Shipped"
                        },
                        new
                        {
                            OrderStatusId = 3,
                            Description = "Delivered"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            Description = "Paid"
                        });
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillingAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalesTax")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("PurchaseOrder", (string)null);

                    b.HasData(
                        new
                        {
                            PurchaseOrderId = 5001,
                            BillingAddressId = 10003,
                            CustomerId = 1001,
                            Date = new DateOnly(2023, 10, 22),
                            Note = "November Resupply",
                            Number = "NN6003",
                            SalesTax = 0.0543m,
                            ShippingAddressId = 10003
                        });
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("PurchaseOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventroyItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("NUMERIC");

                    b.HasKey("PurchaseOrderDetailId");

                    b.HasIndex("InventroyItemId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetail", (string)null);

                    b.HasData(
                        new
                        {
                            PurchaseOrderDetailId = 50001,
                            InventroyItemId = 20001,
                            OrderStatusId = 1,
                            PurchaseOrderId = 5001,
                            Quantity = 3,
                            UnitPrice = 141.95m
                        });
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.State", b =>
                {
                    b.Property<int>("StateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalesTax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMERIC")
                        .HasDefaultValueSql("0");

                    b.HasKey("StateId");

                    b.ToTable("State", (string)null);

                    b.HasData(
                        new
                        {
                            StateId = 17,
                            Code = "IL",
                            Name = "Illinois",
                            SalesTax = 0.0882m
                        },
                        new
                        {
                            StateId = 18,
                            Code = "IN",
                            Name = "Indiana",
                            SalesTax = 0.07m
                        },
                        new
                        {
                            StateId = 26,
                            Code = "MI",
                            Name = "Michigan",
                            SalesTax = 0.06m
                        },
                        new
                        {
                            StateId = 39,
                            Code = "OH",
                            Name = "Ohio",
                            SalesTax = 0.0723m
                        },
                        new
                        {
                            StateId = 55,
                            Code = "WI",
                            Name = "Wisconsin",
                            SalesTax = 0.0543m
                        });
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorId");

                    b.HasIndex("AddressId");

                    b.ToTable("Vendor", (string)null);

                    b.HasData(
                        new
                        {
                            VendorId = 101,
                            AddressId = 10001,
                            Name = "Ox Exports"
                        });
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.Address", b =>
                {
                    b.HasOne("Ch15Lab.Data.Entities.State", "State")
                        .WithMany("Addresses")
                        .HasForeignKey("StateId")
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.Customer", b =>
                {
                    b.HasOne("Ch15Lab.Data.Entities.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("AddressId")
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("Ch15Lab.Data.Entities.Vendor", "Vendor")
                        .WithMany("InventoryItems")
                        .HasForeignKey("VendorId")
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Ch15Lab.Data.Entities.Address", "BillingAddress")
                        .WithMany("PurchaseOrderBillingAddresses")
                        .HasForeignKey("BillingAddressId")
                        .IsRequired();

                    b.HasOne("Ch15Lab.Data.Entities.Customer", "Customer")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.HasOne("Ch15Lab.Data.Entities.Address", "ShippingAddress")
                        .WithMany("PurchaseOrderShippingAddresses")
                        .HasForeignKey("ShippingAddressId")
                        .IsRequired();

                    b.Navigation("BillingAddress");

                    b.Navigation("Customer");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.PurchaseOrderDetail", b =>
                {
                    b.HasOne("Ch15Lab.Data.Entities.InventoryItem", "InventroyItem")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("InventroyItemId")
                        .IsRequired();

                    b.HasOne("Ch15Lab.Data.Entities.OrderStatus", "OrderStatus")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("OrderStatusId")
                        .IsRequired();

                    b.HasOne("Ch15Lab.Data.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId")
                        .IsRequired();

                    b.Navigation("InventroyItem");

                    b.Navigation("OrderStatus");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.Vendor", b =>
                {
                    b.HasOne("Ch15Lab.Data.Entities.Address", "Address")
                        .WithMany("Vendors")
                        .HasForeignKey("AddressId")
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.Address", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("PurchaseOrderBillingAddresses");

                    b.Navigation("PurchaseOrderShippingAddresses");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.Customer", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.InventoryItem", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.OrderStatus", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.State", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Ch15Lab.Data.Entities.Vendor", b =>
                {
                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
